# L04: Data Visualization; Functions

## Goals{#goals04}

- Getting to know the basics of data visualization; writing simple functions (reusable, packaged code)

## Software{#soft04}

* *the same*, with some new libraries:
	* R <https://www.r-project.org/> 
	* R Studio <https://www.rstudio.com/>

## Class{#cLass04}

* Practice worksheets:

- [`05_worksheets_ggplot2-introduction-MGR-mod.Rmd.zip`](./files/05_worksheets_ggplot2-introduction-MGR-mod.Rmd.zip)
- [`06_worksheets_functions.Rmd.zip`](./files/06_worksheets_functions.Rmd.zip)

**NB:** Original worksheets prepared by Lincoln Mullen, GMU (<https://dh-r.lincolnmullen.com/worksheets.html>)


## Topics{#topics04}

- Basics of using `ggplot2`
  - "grammar" of graphics
  - Basic `geoms` in ggplot2
    - Histogram
    - Lines
    - Bar plots
    - Faceting
  - Labels
  - Create your own plots
- Writing your own functions
  - Explanation of functions
  - Function calls
  - Function definition

## Reference materials{#RM04}

Consult relevant chapters from: 

* Healy, Kieran *Data Visualization: A Practical Guide*. Princeton University Press, 2018. ISBN: 978-0691181622. <http://socviz.co/>
* Hadley Wickham & Garrett Grolemund, *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data.* O’Reilly, 2017. ISBN: 978-1491910399. <https://r4ds.had.co.nz/>
* Wickham, Hadley. *Advanced R, Second Edition.* 2 edition. Boca Raton: Chapman and Hall/CRC, 2019. <http://adv-r.had.co.nz/>


## Homework{#HW04}

- Finish your worksheet and submit your HW as described below.
* *Additional:* if you'd like more practice, you can use `swirl` library:
  * To install: `install.packages("swirl")`
  * To run: `library(swirl)`
    * Then: `swirl()`
    * it will offer you a set of interactive exercises similar to DataCamp.

## Submitting homework{#SHW04}

* Homework assignment must be submitted by the beginning of the next class;
* Email your homework to the instructor as attachments.
	*  In the subject of your email, please, add the following: `57528-LXX-HW-YourLastName-YourMatriculationNumber`, where `LXX` is the number of the lesson for which you submit homework; `YourLastName` is your last name; and `YourMatriculationNumber` is your matriculation number.